<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anndy-PC" ignored="0" name="Test" tests="1" failures="1" timestamp="08 Aug 2019 14:21:42 GMT" time="83.401" errors="0">
  <testcase name="loginCase" time="63.53" classname="cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
at message : 预期为空 实际不为空 expected [true] but found [false] in method : .loginCase(HomeTestCase1:50)
at cn.AnndyTsal.PO.PO_simplify.Case.HomeTestCase1.loginCase(HomeTestCase1.java:50)
]]>
    </failure>
  </testcase> <!-- loginCase -->
</testsuite> <!-- Test -->
